version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks: 
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_ADMIN=${SQL_ADMIN}
        - SQL_USER_PASSWORD=${SQL_USER_PASSWORD}
        - SQL_ADMIN_PASSWORD=${SQL_ADMIN_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
        - SQL_HOST=${SQL_HOST}
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile	
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure
    env_file: 
      - .env

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception
    restart: on-failure
    env_file: 
      - .env
    depends_on:
      - mariadb    

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vahemere/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vahemere/data/wordpress'

networks:
  inception:
    name: inception
